/* automatically generated by rust-bindgen 0.70.0 */

#![allow(non_upper_case_globals)]
#![allow(dead_code)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(clippy::unreadable_literal)]
#![allow(clippy::similar_names)]

pub const WINVER: u32 = 1281;
pub const _LIBC_LIMITS_H_: u32 = 1;
pub const _FEATURES_H: u32 = 1;
pub const _DEFAULT_SOURCE: u32 = 1;
pub const __GLIBC_USE_ISOC23: u32 = 0;
pub const __USE_ISOC11: u32 = 1;
pub const __USE_ISOC99: u32 = 1;
pub const __USE_ISOC95: u32 = 1;
pub const __USE_POSIX_IMPLICITLY: u32 = 1;
pub const _POSIX_SOURCE: u32 = 1;
pub const _POSIX_C_SOURCE: u32 = 200809;
pub const __USE_POSIX: u32 = 1;
pub const __USE_POSIX2: u32 = 1;
pub const __USE_POSIX199309: u32 = 1;
pub const __USE_POSIX199506: u32 = 1;
pub const __USE_XOPEN2K: u32 = 1;
pub const __USE_XOPEN2K8: u32 = 1;
pub const _ATFILE_SOURCE: u32 = 1;
pub const __WORDSIZE: u32 = 64;
pub const __WORDSIZE_TIME64_COMPAT32: u32 = 1;
pub const __SYSCALL_WORDSIZE: u32 = 64;
pub const __TIMESIZE: u32 = 64;
pub const __USE_TIME_BITS64: u32 = 1;
pub const __USE_MISC: u32 = 1;
pub const __USE_ATFILE: u32 = 1;
pub const __USE_FORTIFY_LEVEL: u32 = 0;
pub const __GLIBC_USE_DEPRECATED_GETS: u32 = 0;
pub const __GLIBC_USE_DEPRECATED_SCANF: u32 = 0;
pub const __GLIBC_USE_C23_STRTOL: u32 = 0;
pub const _STDC_PREDEF_H: u32 = 1;
pub const __STDC_IEC_559__: u32 = 1;
pub const __STDC_IEC_60559_BFP__: u32 = 201404;
pub const __STDC_IEC_559_COMPLEX__: u32 = 1;
pub const __STDC_IEC_60559_COMPLEX__: u32 = 201404;
pub const __STDC_ISO_10646__: u32 = 201706;
pub const __GNU_LIBRARY__: u32 = 6;
pub const __GLIBC__: u32 = 2;
pub const __GLIBC_MINOR__: u32 = 40;
pub const _SYS_CDEFS_H: u32 = 1;
pub const __glibc_c99_flexarr_available: u32 = 1;
pub const __LDOUBLE_REDIRECTS_TO_FLOAT128_ABI: u32 = 0;
pub const __HAVE_GENERIC_SELECTION: u32 = 1;
pub const __GLIBC_USE_LIB_EXT2: u32 = 0;
pub const __GLIBC_USE_IEC_60559_BFP_EXT: u32 = 0;
pub const __GLIBC_USE_IEC_60559_BFP_EXT_C23: u32 = 0;
pub const __GLIBC_USE_IEC_60559_EXT: u32 = 0;
pub const __GLIBC_USE_IEC_60559_FUNCS_EXT: u32 = 0;
pub const __GLIBC_USE_IEC_60559_FUNCS_EXT_C23: u32 = 0;
pub const __GLIBC_USE_IEC_60559_TYPES_EXT: u32 = 0;
pub const MB_LEN_MAX: u32 = 16;
pub const _BITS_POSIX1_LIM_H: u32 = 1;
pub const _POSIX_AIO_LISTIO_MAX: u32 = 2;
pub const _POSIX_AIO_MAX: u32 = 1;
pub const _POSIX_ARG_MAX: u32 = 4096;
pub const _POSIX_CHILD_MAX: u32 = 25;
pub const _POSIX_DELAYTIMER_MAX: u32 = 32;
pub const _POSIX_HOST_NAME_MAX: u32 = 255;
pub const _POSIX_LINK_MAX: u32 = 8;
pub const _POSIX_LOGIN_NAME_MAX: u32 = 9;
pub const _POSIX_MAX_CANON: u32 = 255;
pub const _POSIX_MAX_INPUT: u32 = 255;
pub const _POSIX_MQ_OPEN_MAX: u32 = 8;
pub const _POSIX_MQ_PRIO_MAX: u32 = 32;
pub const _POSIX_NAME_MAX: u32 = 14;
pub const _POSIX_NGROUPS_MAX: u32 = 8;
pub const _POSIX_OPEN_MAX: u32 = 20;
pub const _POSIX_PATH_MAX: u32 = 256;
pub const _POSIX_PIPE_BUF: u32 = 512;
pub const _POSIX_RE_DUP_MAX: u32 = 255;
pub const _POSIX_RTSIG_MAX: u32 = 8;
pub const _POSIX_SEM_NSEMS_MAX: u32 = 256;
pub const _POSIX_SEM_VALUE_MAX: u32 = 32767;
pub const _POSIX_SIGQUEUE_MAX: u32 = 32;
pub const _POSIX_SSIZE_MAX: u32 = 32767;
pub const _POSIX_STREAM_MAX: u32 = 8;
pub const _POSIX_SYMLINK_MAX: u32 = 255;
pub const _POSIX_SYMLOOP_MAX: u32 = 8;
pub const _POSIX_TIMER_MAX: u32 = 32;
pub const _POSIX_TTY_NAME_MAX: u32 = 9;
pub const _POSIX_TZNAME_MAX: u32 = 6;
pub const _POSIX_CLOCKRES_MIN: u32 = 20000000;
pub const NR_OPEN: u32 = 1024;
pub const NGROUPS_MAX: u32 = 65536;
pub const ARG_MAX: u32 = 131072;
pub const LINK_MAX: u32 = 127;
pub const MAX_CANON: u32 = 255;
pub const MAX_INPUT: u32 = 255;
pub const NAME_MAX: u32 = 255;
pub const PATH_MAX: u32 = 4096;
pub const PIPE_BUF: u32 = 4096;
pub const XATTR_NAME_MAX: u32 = 255;
pub const XATTR_SIZE_MAX: u32 = 65536;
pub const XATTR_LIST_MAX: u32 = 65536;
pub const RTSIG_MAX: u32 = 32;
pub const _POSIX_THREAD_KEYS_MAX: u32 = 128;
pub const PTHREAD_KEYS_MAX: u32 = 1024;
pub const _POSIX_THREAD_DESTRUCTOR_ITERATIONS: u32 = 4;
pub const PTHREAD_DESTRUCTOR_ITERATIONS: u32 = 4;
pub const _POSIX_THREAD_THREADS_MAX: u32 = 64;
pub const AIO_PRIO_DELTA_MAX: u32 = 20;
pub const PTHREAD_STACK_MIN: u32 = 16384;
pub const DELAYTIMER_MAX: u32 = 2147483647;
pub const TTY_NAME_MAX: u32 = 32;
pub const LOGIN_NAME_MAX: u32 = 256;
pub const HOST_NAME_MAX: u32 = 64;
pub const MQ_PRIO_MAX: u32 = 32768;
pub const SEM_VALUE_MAX: u32 = 2147483647;
pub const _BITS_POSIX2_LIM_H: u32 = 1;
pub const _POSIX2_BC_BASE_MAX: u32 = 99;
pub const _POSIX2_BC_DIM_MAX: u32 = 2048;
pub const _POSIX2_BC_SCALE_MAX: u32 = 99;
pub const _POSIX2_BC_STRING_MAX: u32 = 1000;
pub const _POSIX2_COLL_WEIGHTS_MAX: u32 = 2;
pub const _POSIX2_EXPR_NEST_MAX: u32 = 32;
pub const _POSIX2_LINE_MAX: u32 = 2048;
pub const _POSIX2_RE_DUP_MAX: u32 = 255;
pub const _POSIX2_CHARCLASS_NAME_MAX: u32 = 14;
pub const BC_BASE_MAX: u32 = 99;
pub const BC_DIM_MAX: u32 = 2048;
pub const BC_SCALE_MAX: u32 = 99;
pub const BC_STRING_MAX: u32 = 1000;
pub const COLL_WEIGHTS_MAX: u32 = 255;
pub const EXPR_NEST_MAX: u32 = 32;
pub const LINE_MAX: u32 = 2048;
pub const CHARCLASS_NAME_MAX: u32 = 2048;
pub const RE_DUP_MAX: u32 = 32767;
pub const LUA_MULTILIB: &[u8; 4] = b"lib\0";
pub const LUA_LMULTILIB: &[u8; 4] = b"lib\0";
pub const LUA_LROOT: &[u8; 11] = b"/usr/local\0";
pub const LUA_LUADIR: &[u8; 10] = b"/lua/5.1/\0";
pub const LUA_LJDIR: &[u8; 15] = b"/luajit-2.0.4/\0";
pub const LUA_JROOT: &[u8; 11] = b"/usr/local\0";
pub const LUA_JPATH: &[u8; 37] = b";/usr/local/share/luajit-2.0.4/?.lua\0";
pub const LUA_LLDIR: &[u8; 26] = b"/usr/local/share/lua/5.1/\0";
pub const LUA_LCDIR: &[u8; 24] = b"/usr/local/lib/lua/5.1/\0";
pub const LUA_LLPATH: &[u8; 68] =
    b";/usr/local/share/lua/5.1/?.lua;/usr/local/share/lua/5.1/?/init.lua\0";
pub const LUA_LCPATH1: &[u8; 29] = b";/usr/local/lib/lua/5.1/?.so\0";
pub const LUA_LCPATH2: &[u8; 35] = b";/usr/local/lib/lua/5.1/loadall.so\0";
pub const LUA_PATH: &[u8; 9] = b"LUA_PATH\0";
pub const LUA_CPATH: &[u8; 10] = b"LUA_CPATH\0";
pub const LUA_INIT: &[u8; 9] = b"LUA_INIT\0";
pub const LUA_DIRSEP: &[u8; 2] = b"/\0";
pub const LUA_PATHSEP: &[u8; 2] = b";\0";
pub const LUA_PATH_MARK: &[u8; 2] = b"?\0";
pub const LUA_EXECDIR: &[u8; 2] = b"!\0";
pub const LUA_IGMARK: &[u8; 2] = b"-\0";
pub const LUA_PATH_CONFIG: &[u8; 10] = b"/\n;\n?\n!\n-\0";
pub const LUAI_MAXSTACK: u32 = 65500;
pub const LUAI_MAXCSTACK: u32 = 8000;
pub const LUAI_GCPAUSE: u32 = 200;
pub const LUAI_GCMUL: u32 = 200;
pub const LUA_MAXCAPTURES: u32 = 32;
pub const LUA_IDSIZE: u32 = 60;
pub const LUA_NUMBER_SCAN: &[u8; 4] = b"%lf\0";
pub const LUA_NUMBER_FMT: &[u8; 6] = b"%.14g\0";
pub const LUAI_MAXNUMBER2STR: u32 = 32;
pub const LUA_INTFRMLEN: &[u8; 2] = b"l\0";
pub const LUA_VERSION: &[u8; 8] = b"Lua 5.1\0";
pub const LUA_RELEASE: &[u8; 10] = b"Lua 5.1.4\0";
pub const LUA_VERSION_NUM: u32 = 501;
pub const LUA_COPYRIGHT: &[u8; 41] = b"Copyright (C) 1994-2008 Lua.org, PUC-Rio\0";
pub const LUA_AUTHORS: &[u8; 49] = b"R. Ierusalimschy, L. H. de Figueiredo & W. Celes\0";
pub const LUA_SIGNATURE: &[u8; 5] = b"\x1BLua\0";
pub const LUA_MULTRET: i32 = -1;
pub const LUA_REGISTRYINDEX: i32 = -10000;
pub const LUA_ENVIRONINDEX: i32 = -10001;
pub const LUA_GLOBALSINDEX: i32 = -10002;
pub const LUA_YIELD: u32 = 1;
pub const LUA_ERRRUN: u32 = 2;
pub const LUA_ERRSYNTAX: u32 = 3;
pub const LUA_ERRMEM: u32 = 4;
pub const LUA_ERRERR: u32 = 5;
pub const LUA_TNONE: i32 = -1;
pub const LUA_TNIL: u32 = 0;
pub const LUA_TBOOLEAN: u32 = 1;
pub const LUA_TLIGHTUSERDATA: u32 = 2;
pub const LUA_TNUMBER: u32 = 3;
pub const LUA_TSTRING: u32 = 4;
pub const LUA_TTABLE: u32 = 5;
pub const LUA_TFUNCTION: u32 = 6;
pub const LUA_TUSERDATA: u32 = 7;
pub const LUA_TTHREAD: u32 = 8;
pub const LUA_MINSTACK: u32 = 20;
pub const LUA_GCSTOP: u32 = 0;
pub const LUA_GCRESTART: u32 = 1;
pub const LUA_GCCOLLECT: u32 = 2;
pub const LUA_GCCOUNT: u32 = 3;
pub const LUA_GCCOUNTB: u32 = 4;
pub const LUA_GCSTEP: u32 = 5;
pub const LUA_GCSETPAUSE: u32 = 6;
pub const LUA_GCSETSTEPMUL: u32 = 7;
pub const LUA_HOOKCALL: u32 = 0;
pub const LUA_HOOKRET: u32 = 1;
pub const LUA_HOOKLINE: u32 = 2;
pub const LUA_HOOKCOUNT: u32 = 3;
pub const LUA_HOOKTAILRET: u32 = 4;
pub const LUA_MASKCALL: u32 = 1;
pub const LUA_MASKRET: u32 = 2;
pub const LUA_MASKLINE: u32 = 4;
pub const LUA_MASKCOUNT: u32 = 8;
pub type __gnuc_va_list = __builtin_va_list;
pub type va_list = __builtin_va_list;
pub type wchar_t = std::os::raw::c_int;
#[repr(C)]
#[repr(align(16))]
#[derive(Debug, Copy, Clone)]
pub struct max_align_t {
    pub __clang_max_align_nonce1: std::os::raw::c_longlong,
    pub __bindgen_padding_0: u64,
    pub __clang_max_align_nonce2: u128,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct lua_State {
    _unused: [u8; 0],
}
pub type lua_CFunction = Option<unsafe extern "C" fn(L: *mut lua_State) -> std::os::raw::c_int>;
pub type lua_Reader = Option<
    unsafe extern "C" fn(
        L: *mut lua_State,
        ud: *mut std::os::raw::c_void,
        sz: *mut usize,
    ) -> *const std::os::raw::c_char,
>;
pub type lua_Writer = Option<
    unsafe extern "C" fn(
        L: *mut lua_State,
        p: *const std::os::raw::c_void,
        sz: usize,
        ud: *mut std::os::raw::c_void,
    ) -> std::os::raw::c_int,
>;
pub type lua_Alloc = Option<
    unsafe extern "C" fn(
        ud: *mut std::os::raw::c_void,
        ptr: *mut std::os::raw::c_void,
        osize: usize,
        nsize: usize,
    ) -> *mut std::os::raw::c_void,
>;
pub type lua_Number = f64;
pub type lua_Integer = isize;
pub type lua_Hook = Option<unsafe extern "C" fn(L: *mut lua_State, ar: *mut lua_Debug)>;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct lua_Debug {
    pub event: std::os::raw::c_int,
    pub name: *const std::os::raw::c_char,
    pub namewhat: *const std::os::raw::c_char,
    pub what: *const std::os::raw::c_char,
    pub source: *const std::os::raw::c_char,
    pub currentline: std::os::raw::c_int,
    pub nups: std::os::raw::c_int,
    pub linedefined: std::os::raw::c_int,
    pub lastlinedefined: std::os::raw::c_int,
    pub short_src: [std::os::raw::c_char; 60usize],
    pub i_ci: std::os::raw::c_int,
}
pub type __builtin_va_list = [__va_list_tag; 1usize];
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct __va_list_tag {
    pub gp_offset: std::os::raw::c_uint,
    pub fp_offset: std::os::raw::c_uint,
    pub overflow_arg_area: *mut std::os::raw::c_void,
    pub reg_save_area: *mut std::os::raw::c_void,
}
pub struct Lua51 {
    __library: libloading::Library,
    pub lua_newstate:
        unsafe extern "C" fn(f: lua_Alloc, ud: *mut std::os::raw::c_void) -> *mut lua_State,
    pub lua_close: unsafe extern "C" fn(L: *mut lua_State),
    pub lua_newthread: unsafe extern "C" fn(L: *mut lua_State) -> *mut lua_State,
    pub lua_atpanic:
        unsafe extern "C" fn(L: *mut lua_State, panicf: lua_CFunction) -> lua_CFunction,
    pub lua_gettop: unsafe extern "C" fn(L: *mut lua_State) -> std::os::raw::c_int,
    pub lua_settop: unsafe extern "C" fn(L: *mut lua_State, idx: std::os::raw::c_int),
    pub lua_pushvalue: unsafe extern "C" fn(L: *mut lua_State, idx: std::os::raw::c_int),
    pub lua_remove: unsafe extern "C" fn(L: *mut lua_State, idx: std::os::raw::c_int),
    pub lua_insert: unsafe extern "C" fn(L: *mut lua_State, idx: std::os::raw::c_int),
    pub lua_replace: unsafe extern "C" fn(L: *mut lua_State, idx: std::os::raw::c_int),
    pub lua_checkstack:
        unsafe extern "C" fn(L: *mut lua_State, sz: std::os::raw::c_int) -> std::os::raw::c_int,
    pub lua_xmove:
        unsafe extern "C" fn(from: *mut lua_State, to: *mut lua_State, n: std::os::raw::c_int),
    pub lua_isnumber:
        unsafe extern "C" fn(L: *mut lua_State, idx: std::os::raw::c_int) -> std::os::raw::c_int,
    pub lua_isstring:
        unsafe extern "C" fn(L: *mut lua_State, idx: std::os::raw::c_int) -> std::os::raw::c_int,
    pub lua_iscfunction:
        unsafe extern "C" fn(L: *mut lua_State, idx: std::os::raw::c_int) -> std::os::raw::c_int,
    pub lua_isuserdata:
        unsafe extern "C" fn(L: *mut lua_State, idx: std::os::raw::c_int) -> std::os::raw::c_int,
    pub lua_type:
        unsafe extern "C" fn(L: *mut lua_State, idx: std::os::raw::c_int) -> std::os::raw::c_int,
    pub lua_typename: unsafe extern "C" fn(
        L: *mut lua_State,
        tp: std::os::raw::c_int,
    ) -> *const std::os::raw::c_char,
    pub lua_equal: unsafe extern "C" fn(
        L: *mut lua_State,
        idx1: std::os::raw::c_int,
        idx2: std::os::raw::c_int,
    ) -> std::os::raw::c_int,
    pub lua_rawequal: unsafe extern "C" fn(
        L: *mut lua_State,
        idx1: std::os::raw::c_int,
        idx2: std::os::raw::c_int,
    ) -> std::os::raw::c_int,
    pub lua_lessthan: unsafe extern "C" fn(
        L: *mut lua_State,
        idx1: std::os::raw::c_int,
        idx2: std::os::raw::c_int,
    ) -> std::os::raw::c_int,
    pub lua_tonumber:
        unsafe extern "C" fn(L: *mut lua_State, idx: std::os::raw::c_int) -> lua_Number,
    pub lua_tointeger:
        unsafe extern "C" fn(L: *mut lua_State, idx: std::os::raw::c_int) -> lua_Integer,
    pub lua_toboolean:
        unsafe extern "C" fn(L: *mut lua_State, idx: std::os::raw::c_int) -> std::os::raw::c_int,
    pub lua_tolstring: unsafe extern "C" fn(
        L: *mut lua_State,
        idx: std::os::raw::c_int,
        len: *mut usize,
    ) -> *const std::os::raw::c_char,
    pub lua_objlen: unsafe extern "C" fn(L: *mut lua_State, idx: std::os::raw::c_int) -> usize,
    pub lua_tocfunction:
        unsafe extern "C" fn(L: *mut lua_State, idx: std::os::raw::c_int) -> lua_CFunction,
    pub lua_touserdata: unsafe extern "C" fn(
        L: *mut lua_State,
        idx: std::os::raw::c_int,
    ) -> *mut std::os::raw::c_void,
    pub lua_tothread:
        unsafe extern "C" fn(L: *mut lua_State, idx: std::os::raw::c_int) -> *mut lua_State,
    pub lua_topointer: unsafe extern "C" fn(
        L: *mut lua_State,
        idx: std::os::raw::c_int,
    ) -> *const std::os::raw::c_void,
    pub lua_pushnil: unsafe extern "C" fn(L: *mut lua_State),
    pub lua_pushnumber: unsafe extern "C" fn(L: *mut lua_State, n: lua_Number),
    pub lua_pushinteger: unsafe extern "C" fn(L: *mut lua_State, n: lua_Integer),
    pub lua_pushlstring:
        unsafe extern "C" fn(L: *mut lua_State, s: *const std::os::raw::c_char, l: usize),
    pub lua_pushstring: unsafe extern "C" fn(L: *mut lua_State, s: *const std::os::raw::c_char),
    pub lua_pushvfstring: unsafe extern "C" fn(
        L: *mut lua_State,
        fmt: *const std::os::raw::c_char,
        argp: *mut __va_list_tag,
    ) -> *const std::os::raw::c_char,
    pub lua_pushfstring: unsafe extern "C" fn(
        L: *mut lua_State,
        fmt: *const std::os::raw::c_char,
        ...
    ) -> *const std::os::raw::c_char,
    pub lua_pushcclosure:
        unsafe extern "C" fn(L: *mut lua_State, fn_: lua_CFunction, n: std::os::raw::c_int),
    pub lua_pushboolean: unsafe extern "C" fn(L: *mut lua_State, b: std::os::raw::c_int),
    pub lua_pushlightuserdata:
        unsafe extern "C" fn(L: *mut lua_State, p: *mut std::os::raw::c_void),
    pub lua_pushthread: unsafe extern "C" fn(L: *mut lua_State) -> std::os::raw::c_int,
    pub lua_gettable: unsafe extern "C" fn(L: *mut lua_State, idx: std::os::raw::c_int),
    pub lua_getfield: unsafe extern "C" fn(
        L: *mut lua_State,
        idx: std::os::raw::c_int,
        k: *const std::os::raw::c_char,
    ),
    pub lua_rawget: unsafe extern "C" fn(L: *mut lua_State, idx: std::os::raw::c_int),
    pub lua_rawgeti:
        unsafe extern "C" fn(L: *mut lua_State, idx: std::os::raw::c_int, n: std::os::raw::c_int),
    pub lua_createtable: unsafe extern "C" fn(
        L: *mut lua_State,
        narr: std::os::raw::c_int,
        nrec: std::os::raw::c_int,
    ),
    pub lua_newuserdata:
        unsafe extern "C" fn(L: *mut lua_State, sz: usize) -> *mut std::os::raw::c_void,
    pub lua_getmetatable: unsafe extern "C" fn(
        L: *mut lua_State,
        objindex: std::os::raw::c_int,
    ) -> std::os::raw::c_int,
    pub lua_getfenv: unsafe extern "C" fn(L: *mut lua_State, idx: std::os::raw::c_int),
    pub lua_settable: unsafe extern "C" fn(L: *mut lua_State, idx: std::os::raw::c_int),
    pub lua_setfield: unsafe extern "C" fn(
        L: *mut lua_State,
        idx: std::os::raw::c_int,
        k: *const std::os::raw::c_char,
    ),
    pub lua_rawset: unsafe extern "C" fn(L: *mut lua_State, idx: std::os::raw::c_int),
    pub lua_rawseti:
        unsafe extern "C" fn(L: *mut lua_State, idx: std::os::raw::c_int, n: std::os::raw::c_int),
    pub lua_setmetatable: unsafe extern "C" fn(
        L: *mut lua_State,
        objindex: std::os::raw::c_int,
    ) -> std::os::raw::c_int,
    pub lua_setfenv:
        unsafe extern "C" fn(L: *mut lua_State, idx: std::os::raw::c_int) -> std::os::raw::c_int,
    pub lua_call: unsafe extern "C" fn(
        L: *mut lua_State,
        nargs: std::os::raw::c_int,
        nresults: std::os::raw::c_int,
    ),
    pub lua_pcall: unsafe extern "C" fn(
        L: *mut lua_State,
        nargs: std::os::raw::c_int,
        nresults: std::os::raw::c_int,
        errfunc: std::os::raw::c_int,
    ) -> std::os::raw::c_int,
    pub lua_cpcall: unsafe extern "C" fn(
        L: *mut lua_State,
        func: lua_CFunction,
        ud: *mut std::os::raw::c_void,
    ) -> std::os::raw::c_int,
    pub lua_load: unsafe extern "C" fn(
        L: *mut lua_State,
        reader: lua_Reader,
        dt: *mut std::os::raw::c_void,
        chunkname: *const std::os::raw::c_char,
    ) -> std::os::raw::c_int,
    pub lua_dump: unsafe extern "C" fn(
        L: *mut lua_State,
        writer: lua_Writer,
        data: *mut std::os::raw::c_void,
    ) -> std::os::raw::c_int,
    pub lua_yield: unsafe extern "C" fn(
        L: *mut lua_State,
        nresults: std::os::raw::c_int,
    ) -> std::os::raw::c_int,
    pub lua_resume:
        unsafe extern "C" fn(L: *mut lua_State, narg: std::os::raw::c_int) -> std::os::raw::c_int,
    pub lua_status: unsafe extern "C" fn(L: *mut lua_State) -> std::os::raw::c_int,
    pub lua_gc: unsafe extern "C" fn(
        L: *mut lua_State,
        what: std::os::raw::c_int,
        data: std::os::raw::c_int,
    ) -> std::os::raw::c_int,
    pub lua_error: unsafe extern "C" fn(L: *mut lua_State) -> std::os::raw::c_int,
    pub lua_next:
        unsafe extern "C" fn(L: *mut lua_State, idx: std::os::raw::c_int) -> std::os::raw::c_int,
    pub lua_concat: unsafe extern "C" fn(L: *mut lua_State, n: std::os::raw::c_int),
    pub lua_getallocf:
        unsafe extern "C" fn(L: *mut lua_State, ud: *mut *mut std::os::raw::c_void) -> lua_Alloc,
    pub lua_setallocf:
        unsafe extern "C" fn(L: *mut lua_State, f: lua_Alloc, ud: *mut std::os::raw::c_void),
    pub luaL_newstate: unsafe extern "C" fn() -> *mut lua_State,
    //pub lua_setlevel: unsafe extern "C" fn(from: *mut lua_State, to: *mut lua_State),
    pub lua_getstack: unsafe extern "C" fn(
        L: *mut lua_State,
        level: std::os::raw::c_int,
        ar: *mut lua_Debug,
    ) -> std::os::raw::c_int,
    pub lua_getinfo: unsafe extern "C" fn(
        L: *mut lua_State,
        what: *const std::os::raw::c_char,
        ar: *mut lua_Debug,
    ) -> std::os::raw::c_int,
    pub lua_getlocal: unsafe extern "C" fn(
        L: *mut lua_State,
        ar: *const lua_Debug,
        n: std::os::raw::c_int,
    ) -> *const std::os::raw::c_char,
    pub lua_setlocal: unsafe extern "C" fn(
        L: *mut lua_State,
        ar: *const lua_Debug,
        n: std::os::raw::c_int,
    ) -> *const std::os::raw::c_char,
    pub lua_getupvalue: unsafe extern "C" fn(
        L: *mut lua_State,
        funcindex: std::os::raw::c_int,
        n: std::os::raw::c_int,
    ) -> *const std::os::raw::c_char,
    pub lua_setupvalue: unsafe extern "C" fn(
        L: *mut lua_State,
        funcindex: std::os::raw::c_int,
        n: std::os::raw::c_int,
    ) -> *const std::os::raw::c_char,
    pub lua_sethook: unsafe extern "C" fn(
        L: *mut lua_State,
        func: lua_Hook,
        mask: std::os::raw::c_int,
        count: std::os::raw::c_int,
    ) -> std::os::raw::c_int,
    pub lua_gethook: unsafe extern "C" fn(L: *mut lua_State) -> lua_Hook,
    pub lua_gethookmask: unsafe extern "C" fn(L: *mut lua_State) -> std::os::raw::c_int,
    pub lua_gethookcount: unsafe extern "C" fn(L: *mut lua_State) -> std::os::raw::c_int,
    pub lua_upvalueid: unsafe extern "C" fn(
        L: *mut lua_State,
        idx: std::os::raw::c_int,
        n: std::os::raw::c_int,
    ) -> *mut std::os::raw::c_void,
    pub lua_upvaluejoin: unsafe extern "C" fn(
        L: *mut lua_State,
        idx1: std::os::raw::c_int,
        n1: std::os::raw::c_int,
        idx2: std::os::raw::c_int,
        n2: std::os::raw::c_int,
    ),
    pub lua_loadx: unsafe extern "C" fn(
        L: *mut lua_State,
        reader: lua_Reader,
        dt: *mut std::os::raw::c_void,
        chunkname: *const std::os::raw::c_char,
        mode: *const std::os::raw::c_char,
    ) -> std::os::raw::c_int,
}

#[allow(clippy::missing_safety_doc)]
impl Lua51 {
    pub unsafe fn new<P>(path: P) -> Result<Self, libloading::Error>
    where
        P: libloading::AsFilename,
    {
        unsafe {
            let library = libloading::Library::new(path)?;
            Self::from_library(library)
        }
    }
    pub unsafe fn from_library<L>(library: L) -> Result<Self, libloading::Error>
    where
        L: Into<libloading::Library>,
    {
        unsafe {
            let __library = library.into();
            let lua_newstate = __library.get(b"lua_newstate\0").map(|sym| *sym)?;
            let lua_close = __library.get(b"lua_close\0").map(|sym| *sym)?;
            let lua_newthread = __library.get(b"lua_newthread\0").map(|sym| *sym)?;
            let lua_atpanic = __library.get(b"lua_atpanic\0").map(|sym| *sym)?;
            let lua_gettop = __library.get(b"lua_gettop\0").map(|sym| *sym)?;
            let lua_settop = __library.get(b"lua_settop\0").map(|sym| *sym)?;
            let lua_pushvalue = __library.get(b"lua_pushvalue\0").map(|sym| *sym)?;
            let lua_remove = __library.get(b"lua_remove\0").map(|sym| *sym)?;
            let lua_insert = __library.get(b"lua_insert\0").map(|sym| *sym)?;
            let lua_replace = __library.get(b"lua_replace\0").map(|sym| *sym)?;
            let lua_checkstack = __library.get(b"lua_checkstack\0").map(|sym| *sym)?;
            let lua_xmove = __library.get(b"lua_xmove\0").map(|sym| *sym)?;
            let lua_isnumber = __library.get(b"lua_isnumber\0").map(|sym| *sym)?;
            let lua_isstring = __library.get(b"lua_isstring\0").map(|sym| *sym)?;
            let lua_iscfunction = __library.get(b"lua_iscfunction\0").map(|sym| *sym)?;
            let lua_isuserdata = __library.get(b"lua_isuserdata\0").map(|sym| *sym)?;
            let lua_type = __library.get(b"lua_type\0").map(|sym| *sym)?;
            let lua_typename = __library.get(b"lua_typename\0").map(|sym| *sym)?;
            let lua_equal = __library.get(b"lua_equal\0").map(|sym| *sym)?;
            let lua_rawequal = __library.get(b"lua_rawequal\0").map(|sym| *sym)?;
            let lua_lessthan = __library.get(b"lua_lessthan\0").map(|sym| *sym)?;
            let lua_tonumber = __library.get(b"lua_tonumber\0").map(|sym| *sym)?;
            let lua_tointeger = __library.get(b"lua_tointeger\0").map(|sym| *sym)?;
            let lua_toboolean = __library.get(b"lua_toboolean\0").map(|sym| *sym)?;
            let lua_tolstring = __library.get(b"lua_tolstring\0").map(|sym| *sym)?;
            let lua_objlen = __library.get(b"lua_objlen\0").map(|sym| *sym)?;
            let lua_tocfunction = __library.get(b"lua_tocfunction\0").map(|sym| *sym)?;
            let lua_touserdata = __library.get(b"lua_touserdata\0").map(|sym| *sym)?;
            let lua_tothread = __library.get(b"lua_tothread\0").map(|sym| *sym)?;
            let lua_topointer = __library.get(b"lua_topointer\0").map(|sym| *sym)?;
            let lua_pushnil = __library.get(b"lua_pushnil\0").map(|sym| *sym)?;
            let lua_pushnumber = __library.get(b"lua_pushnumber\0").map(|sym| *sym)?;
            let lua_pushinteger = __library.get(b"lua_pushinteger\0").map(|sym| *sym)?;
            let lua_pushlstring = __library.get(b"lua_pushlstring\0").map(|sym| *sym)?;
            let lua_pushstring = __library.get(b"lua_pushstring\0").map(|sym| *sym)?;
            let lua_pushvfstring = __library.get(b"lua_pushvfstring\0").map(|sym| *sym)?;
            let lua_pushfstring = __library.get(b"lua_pushfstring\0").map(|sym| *sym)?;
            let lua_pushcclosure = __library.get(b"lua_pushcclosure\0").map(|sym| *sym)?;
            let lua_pushboolean = __library.get(b"lua_pushboolean\0").map(|sym| *sym)?;
            let lua_pushlightuserdata =
                __library.get(b"lua_pushlightuserdata\0").map(|sym| *sym)?;
            let lua_pushthread = __library.get(b"lua_pushthread\0").map(|sym| *sym)?;
            let lua_gettable = __library.get(b"lua_gettable\0").map(|sym| *sym)?;
            let lua_getfield = __library.get(b"lua_getfield\0").map(|sym| *sym)?;
            let lua_rawget = __library.get(b"lua_rawget\0").map(|sym| *sym)?;
            let lua_rawgeti = __library.get(b"lua_rawgeti\0").map(|sym| *sym)?;
            let lua_createtable = __library.get(b"lua_createtable\0").map(|sym| *sym)?;
            let lua_newuserdata = __library.get(b"lua_newuserdata\0").map(|sym| *sym)?;
            let lua_getmetatable = __library.get(b"lua_getmetatable\0").map(|sym| *sym)?;
            let lua_getfenv = __library.get(b"lua_getfenv\0").map(|sym| *sym)?;
            let lua_settable = __library.get(b"lua_settable\0").map(|sym| *sym)?;
            let lua_setfield = __library.get(b"lua_setfield\0").map(|sym| *sym)?;
            let lua_rawset = __library.get(b"lua_rawset\0").map(|sym| *sym)?;
            let lua_rawseti = __library.get(b"lua_rawseti\0").map(|sym| *sym)?;
            let lua_setmetatable = __library.get(b"lua_setmetatable\0").map(|sym| *sym)?;
            let lua_setfenv = __library.get(b"lua_setfenv\0").map(|sym| *sym)?;
            let lua_call = __library.get(b"lua_call\0").map(|sym| *sym)?;
            let lua_pcall = __library.get(b"lua_pcall\0").map(|sym| *sym)?;
            let lua_cpcall = __library.get(b"lua_cpcall\0").map(|sym| *sym)?;
            let lua_load = __library.get(b"lua_load\0").map(|sym| *sym)?;
            let lua_dump = __library.get(b"lua_dump\0").map(|sym| *sym)?;
            let lua_yield = __library.get(b"lua_yield\0").map(|sym| *sym)?;
            let lua_resume = __library.get(b"lua_resume\0").map(|sym| *sym)?;
            let lua_status = __library.get(b"lua_status\0").map(|sym| *sym)?;
            let lua_gc = __library.get(b"lua_gc\0").map(|sym| *sym)?;
            let lua_error = __library.get(b"lua_error\0").map(|sym| *sym)?;
            let lua_next = __library.get(b"lua_next\0").map(|sym| *sym)?;
            let lua_concat = __library.get(b"lua_concat\0").map(|sym| *sym)?;
            let lua_getallocf = __library.get(b"lua_getallocf\0").map(|sym| *sym)?;
            let lua_setallocf = __library.get(b"lua_setallocf\0").map(|sym| *sym)?;
            let luaL_newstate = __library.get(b"luaL_newstate\0").map(|sym| *sym)?;
            //let lua_setlevel = __library.get(b"lua_setlevel\0").map(|sym| *sym)?;
            let lua_getstack = __library.get(b"lua_getstack\0").map(|sym| *sym)?;
            let lua_getinfo = __library.get(b"lua_getinfo\0").map(|sym| *sym)?;
            let lua_getlocal = __library.get(b"lua_getlocal\0").map(|sym| *sym)?;
            let lua_setlocal = __library.get(b"lua_setlocal\0").map(|sym| *sym)?;
            let lua_getupvalue = __library.get(b"lua_getupvalue\0").map(|sym| *sym)?;
            let lua_setupvalue = __library.get(b"lua_setupvalue\0").map(|sym| *sym)?;
            let lua_sethook = __library.get(b"lua_sethook\0").map(|sym| *sym)?;
            let lua_gethook = __library.get(b"lua_gethook\0").map(|sym| *sym)?;
            let lua_gethookmask = __library.get(b"lua_gethookmask\0").map(|sym| *sym)?;
            let lua_gethookcount = __library.get(b"lua_gethookcount\0").map(|sym| *sym)?;
            let lua_upvalueid = __library.get(b"lua_upvalueid\0").map(|sym| *sym)?;
            let lua_upvaluejoin = __library.get(b"lua_upvaluejoin\0").map(|sym| *sym)?;
            let lua_loadx = __library.get(b"lua_loadx\0").map(|sym| *sym)?;
            Ok(Lua51 {
                __library,
                lua_newstate,
                lua_close,
                lua_newthread,
                lua_atpanic,
                lua_gettop,
                lua_settop,
                lua_pushvalue,
                lua_remove,
                lua_insert,
                lua_replace,
                lua_checkstack,
                lua_xmove,
                lua_isnumber,
                lua_isstring,
                lua_iscfunction,
                lua_isuserdata,
                lua_type,
                lua_typename,
                lua_equal,
                lua_rawequal,
                lua_lessthan,
                lua_tonumber,
                lua_tointeger,
                lua_toboolean,
                lua_tolstring,
                lua_objlen,
                lua_tocfunction,
                lua_touserdata,
                lua_tothread,
                lua_topointer,
                lua_pushnil,
                lua_pushnumber,
                lua_pushinteger,
                lua_pushlstring,
                lua_pushstring,
                lua_pushvfstring,
                lua_pushfstring,
                lua_pushcclosure,
                lua_pushboolean,
                lua_pushlightuserdata,
                lua_pushthread,
                lua_gettable,
                lua_getfield,
                lua_rawget,
                lua_rawgeti,
                lua_createtable,
                lua_newuserdata,
                lua_getmetatable,
                lua_getfenv,
                lua_settable,
                lua_setfield,
                lua_rawset,
                lua_rawseti,
                lua_setmetatable,
                lua_setfenv,
                lua_call,
                lua_pcall,
                lua_cpcall,
                lua_load,
                lua_dump,
                lua_yield,
                lua_resume,
                lua_status,
                lua_gc,
                lua_error,
                lua_next,
                lua_concat,
                lua_getallocf,
                lua_setallocf,
                luaL_newstate,
                //lua_setlevel,
                lua_getstack,
                lua_getinfo,
                lua_getlocal,
                lua_setlocal,
                lua_getupvalue,
                lua_setupvalue,
                lua_sethook,
                lua_gethook,
                lua_gethookmask,
                lua_gethookcount,
                lua_upvalueid,
                lua_upvaluejoin,
                lua_loadx,
            })
        }
    }
}
