/* automatically generated by rust-bindgen 0.70.0 */

#![allow(non_upper_case_globals)]
#![allow(dead_code)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(clippy::unreadable_literal)]
#![allow(clippy::similar_names)]
#![allow(clippy::pub_underscore_fields)]
use noita_api_macros::gen_stubs;
pub const WINVER: u32 = 1281;
pub const _LIBC_LIMITS_H_: u32 = 1;
pub const _FEATURES_H: u32 = 1;
pub const _DEFAULT_SOURCE: u32 = 1;
pub const __GLIBC_USE_ISOC23: u32 = 0;
pub const __USE_ISOC11: u32 = 1;
pub const __USE_ISOC99: u32 = 1;
pub const __USE_ISOC95: u32 = 1;
pub const __USE_POSIX_IMPLICITLY: u32 = 1;
pub const _POSIX_SOURCE: u32 = 1;
pub const _POSIX_C_SOURCE: u32 = 200809;
pub const __USE_POSIX: u32 = 1;
pub const __USE_POSIX2: u32 = 1;
pub const __USE_POSIX199309: u32 = 1;
pub const __USE_POSIX199506: u32 = 1;
pub const __USE_XOPEN2K: u32 = 1;
pub const __USE_XOPEN2K8: u32 = 1;
pub const _ATFILE_SOURCE: u32 = 1;
pub const __WORDSIZE: u32 = 64;
pub const __WORDSIZE_TIME64_COMPAT32: u32 = 1;
pub const __SYSCALL_WORDSIZE: u32 = 64;
pub const __TIMESIZE: u32 = 64;
pub const __USE_TIME_BITS64: u32 = 1;
pub const __USE_MISC: u32 = 1;
pub const __USE_ATFILE: u32 = 1;
pub const __USE_FORTIFY_LEVEL: u32 = 0;
pub const __GLIBC_USE_DEPRECATED_GETS: u32 = 0;
pub const __GLIBC_USE_DEPRECATED_SCANF: u32 = 0;
pub const __GLIBC_USE_C23_STRTOL: u32 = 0;
pub const _STDC_PREDEF_H: u32 = 1;
pub const __STDC_IEC_559__: u32 = 1;
pub const __STDC_IEC_60559_BFP__: u32 = 201404;
pub const __STDC_IEC_559_COMPLEX__: u32 = 1;
pub const __STDC_IEC_60559_COMPLEX__: u32 = 201404;
pub const __STDC_ISO_10646__: u32 = 201706;
pub const __GNU_LIBRARY__: u32 = 6;
pub const __GLIBC__: u32 = 2;
pub const __GLIBC_MINOR__: u32 = 40;
pub const _SYS_CDEFS_H: u32 = 1;
pub const __glibc_c99_flexarr_available: u32 = 1;
pub const __LDOUBLE_REDIRECTS_TO_FLOAT128_ABI: u32 = 0;
pub const __HAVE_GENERIC_SELECTION: u32 = 1;
pub const __GLIBC_USE_LIB_EXT2: u32 = 0;
pub const __GLIBC_USE_IEC_60559_BFP_EXT: u32 = 0;
pub const __GLIBC_USE_IEC_60559_BFP_EXT_C23: u32 = 0;
pub const __GLIBC_USE_IEC_60559_EXT: u32 = 0;
pub const __GLIBC_USE_IEC_60559_FUNCS_EXT: u32 = 0;
pub const __GLIBC_USE_IEC_60559_FUNCS_EXT_C23: u32 = 0;
pub const __GLIBC_USE_IEC_60559_TYPES_EXT: u32 = 0;
pub const MB_LEN_MAX: u32 = 16;
pub const _BITS_POSIX1_LIM_H: u32 = 1;
pub const _POSIX_AIO_LISTIO_MAX: u32 = 2;
pub const _POSIX_AIO_MAX: u32 = 1;
pub const _POSIX_ARG_MAX: u32 = 4096;
pub const _POSIX_CHILD_MAX: u32 = 25;
pub const _POSIX_DELAYTIMER_MAX: u32 = 32;
pub const _POSIX_HOST_NAME_MAX: u32 = 255;
pub const _POSIX_LINK_MAX: u32 = 8;
pub const _POSIX_LOGIN_NAME_MAX: u32 = 9;
pub const _POSIX_MAX_CANON: u32 = 255;
pub const _POSIX_MAX_INPUT: u32 = 255;
pub const _POSIX_MQ_OPEN_MAX: u32 = 8;
pub const _POSIX_MQ_PRIO_MAX: u32 = 32;
pub const _POSIX_NAME_MAX: u32 = 14;
pub const _POSIX_NGROUPS_MAX: u32 = 8;
pub const _POSIX_OPEN_MAX: u32 = 20;
pub const _POSIX_PATH_MAX: u32 = 256;
pub const _POSIX_PIPE_BUF: u32 = 512;
pub const _POSIX_RE_DUP_MAX: u32 = 255;
pub const _POSIX_RTSIG_MAX: u32 = 8;
pub const _POSIX_SEM_NSEMS_MAX: u32 = 256;
pub const _POSIX_SEM_VALUE_MAX: u32 = 32767;
pub const _POSIX_SIGQUEUE_MAX: u32 = 32;
pub const _POSIX_SSIZE_MAX: u32 = 32767;
pub const _POSIX_STREAM_MAX: u32 = 8;
pub const _POSIX_SYMLINK_MAX: u32 = 255;
pub const _POSIX_SYMLOOP_MAX: u32 = 8;
pub const _POSIX_TIMER_MAX: u32 = 32;
pub const _POSIX_TTY_NAME_MAX: u32 = 9;
pub const _POSIX_TZNAME_MAX: u32 = 6;
pub const _POSIX_CLOCKRES_MIN: u32 = 20000000;
pub const NR_OPEN: u32 = 1024;
pub const NGROUPS_MAX: u32 = 65536;
pub const ARG_MAX: u32 = 131072;
pub const LINK_MAX: u32 = 127;
pub const MAX_CANON: u32 = 255;
pub const MAX_INPUT: u32 = 255;
pub const NAME_MAX: u32 = 255;
pub const PATH_MAX: u32 = 4096;
pub const PIPE_BUF: u32 = 4096;
pub const XATTR_NAME_MAX: u32 = 255;
pub const XATTR_SIZE_MAX: u32 = 65536;
pub const XATTR_LIST_MAX: u32 = 65536;
pub const RTSIG_MAX: u32 = 32;
pub const _POSIX_THREAD_KEYS_MAX: u32 = 128;
pub const PTHREAD_KEYS_MAX: u32 = 1024;
pub const _POSIX_THREAD_DESTRUCTOR_ITERATIONS: u32 = 4;
pub const PTHREAD_DESTRUCTOR_ITERATIONS: u32 = 4;
pub const _POSIX_THREAD_THREADS_MAX: u32 = 64;
pub const AIO_PRIO_DELTA_MAX: u32 = 20;
pub const PTHREAD_STACK_MIN: u32 = 16384;
pub const DELAYTIMER_MAX: u32 = 2147483647;
pub const TTY_NAME_MAX: u32 = 32;
pub const LOGIN_NAME_MAX: u32 = 256;
pub const HOST_NAME_MAX: u32 = 64;
pub const MQ_PRIO_MAX: u32 = 32768;
pub const SEM_VALUE_MAX: u32 = 2147483647;
pub const _BITS_POSIX2_LIM_H: u32 = 1;
pub const _POSIX2_BC_BASE_MAX: u32 = 99;
pub const _POSIX2_BC_DIM_MAX: u32 = 2048;
pub const _POSIX2_BC_SCALE_MAX: u32 = 99;
pub const _POSIX2_BC_STRING_MAX: u32 = 1000;
pub const _POSIX2_COLL_WEIGHTS_MAX: u32 = 2;
pub const _POSIX2_EXPR_NEST_MAX: u32 = 32;
pub const _POSIX2_LINE_MAX: u32 = 2048;
pub const _POSIX2_RE_DUP_MAX: u32 = 255;
pub const _POSIX2_CHARCLASS_NAME_MAX: u32 = 14;
pub const BC_BASE_MAX: u32 = 99;
pub const BC_DIM_MAX: u32 = 2048;
pub const BC_SCALE_MAX: u32 = 99;
pub const BC_STRING_MAX: u32 = 1000;
pub const COLL_WEIGHTS_MAX: u32 = 255;
pub const EXPR_NEST_MAX: u32 = 32;
pub const LINE_MAX: u32 = 2048;
pub const CHARCLASS_NAME_MAX: u32 = 2048;
pub const RE_DUP_MAX: u32 = 32767;
pub const LUA_MULTILIB: &[u8; 4] = b"lib\0";
pub const LUA_LMULTILIB: &[u8; 4] = b"lib\0";
pub const LUA_LROOT: &[u8; 11] = b"/usr/local\0";
pub const LUA_LUADIR: &[u8; 10] = b"/lua/5.1/\0";
pub const LUA_LJDIR: &[u8; 15] = b"/luajit-2.0.4/\0";
pub const LUA_JROOT: &[u8; 11] = b"/usr/local\0";
pub const LUA_JPATH: &[u8; 37] = b";/usr/local/share/luajit-2.0.4/?.lua\0";
pub const LUA_LLDIR: &[u8; 26] = b"/usr/local/share/lua/5.1/\0";
pub const LUA_LCDIR: &[u8; 24] = b"/usr/local/lib/lua/5.1/\0";
pub const LUA_LLPATH: &[u8; 68] =
    b";/usr/local/share/lua/5.1/?.lua;/usr/local/share/lua/5.1/?/init.lua\0";
pub const LUA_LCPATH1: &[u8; 29] = b";/usr/local/lib/lua/5.1/?.so\0";
pub const LUA_LCPATH2: &[u8; 35] = b";/usr/local/lib/lua/5.1/loadall.so\0";
pub const LUA_PATH: &[u8; 9] = b"LUA_PATH\0";
pub const LUA_CPATH: &[u8; 10] = b"LUA_CPATH\0";
pub const LUA_INIT: &[u8; 9] = b"LUA_INIT\0";
pub const LUA_DIRSEP: &[u8; 2] = b"/\0";
pub const LUA_PATHSEP: &[u8; 2] = b";\0";
pub const LUA_PATH_MARK: &[u8; 2] = b"?\0";
pub const LUA_EXECDIR: &[u8; 2] = b"!\0";
pub const LUA_IGMARK: &[u8; 2] = b"-\0";
pub const LUA_PATH_CONFIG: &[u8; 10] = b"/\n;\n?\n!\n-\0";
pub const LUAI_MAXSTACK: u32 = 65500;
pub const LUAI_MAXCSTACK: u32 = 8000;
pub const LUAI_GCPAUSE: u32 = 200;
pub const LUAI_GCMUL: u32 = 200;
pub const LUA_MAXCAPTURES: u32 = 32;
pub const LUA_IDSIZE: u32 = 60;
pub const LUA_NUMBER_SCAN: &[u8; 4] = b"%lf\0";
pub const LUA_NUMBER_FMT: &[u8; 6] = b"%.14g\0";
pub const LUAI_MAXNUMBER2STR: u32 = 32;
pub const LUA_INTFRMLEN: &[u8; 2] = b"l\0";
pub const LUA_VERSION: &[u8; 8] = b"Lua 5.1\0";
pub const LUA_RELEASE: &[u8; 10] = b"Lua 5.1.4\0";
pub const LUA_VERSION_NUM: u32 = 501;
pub const LUA_COPYRIGHT: &[u8; 41] = b"Copyright (C) 1994-2008 Lua.org, PUC-Rio\0";
pub const LUA_AUTHORS: &[u8; 49] = b"R. Ierusalimschy, L. H. de Figueiredo & W. Celes\0";
pub const LUA_SIGNATURE: &[u8; 5] = b"\x1BLua\0";
pub const LUA_MULTRET: i32 = -1;
pub const LUA_REGISTRYINDEX: i32 = -10000;
pub const LUA_ENVIRONINDEX: i32 = -10001;
pub const LUA_GLOBALSINDEX: i32 = -10002;
pub const LUA_YIELD: u32 = 1;
pub const LUA_ERRRUN: u32 = 2;
pub const LUA_ERRSYNTAX: u32 = 3;
pub const LUA_ERRMEM: u32 = 4;
pub const LUA_ERRERR: u32 = 5;
pub const LUA_TNONE: i32 = -1;
pub const LUA_TNIL: u32 = 0;
pub const LUA_TBOOLEAN: u32 = 1;
pub const LUA_TLIGHTUSERDATA: u32 = 2;
pub const LUA_TNUMBER: u32 = 3;
pub const LUA_TSTRING: u32 = 4;
pub const LUA_TTABLE: u32 = 5;
pub const LUA_TFUNCTION: u32 = 6;
pub const LUA_TUSERDATA: u32 = 7;
pub const LUA_TTHREAD: u32 = 8;
pub const LUA_MINSTACK: u32 = 20;
pub const LUA_GCSTOP: u32 = 0;
pub const LUA_GCRESTART: u32 = 1;
pub const LUA_GCCOLLECT: u32 = 2;
pub const LUA_GCCOUNT: u32 = 3;
pub const LUA_GCCOUNTB: u32 = 4;
pub const LUA_GCSTEP: u32 = 5;
pub const LUA_GCSETPAUSE: u32 = 6;
pub const LUA_GCSETSTEPMUL: u32 = 7;
pub const LUA_HOOKCALL: u32 = 0;
pub const LUA_HOOKRET: u32 = 1;
pub const LUA_HOOKLINE: u32 = 2;
pub const LUA_HOOKCOUNT: u32 = 3;
pub const LUA_HOOKTAILRET: u32 = 4;
pub const LUA_MASKCALL: u32 = 1;
pub const LUA_MASKRET: u32 = 2;
pub const LUA_MASKLINE: u32 = 4;
pub const LUA_MASKCOUNT: u32 = 8;
pub type __gnuc_va_list = __builtin_va_list;
pub type va_list = __builtin_va_list;
pub type wchar_t = std::os::raw::c_int;
#[repr(C)]
#[repr(align(16))]
#[derive(Debug, Copy, Clone)]
pub struct max_align_t {
    pub __clang_max_align_nonce1: std::os::raw::c_longlong,
    pub __bindgen_padding_0: u64,
    pub __clang_max_align_nonce2: u128,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct lua_State {
    _unused: [u8; 0],
}
pub type lua_CFunction = Option<unsafe extern "C" fn(L: *mut lua_State) -> std::os::raw::c_int>;
pub type lua_Reader = Option<
    unsafe extern "C" fn(
        L: *mut lua_State,
        ud: *mut std::os::raw::c_void,
        sz: *mut usize,
    ) -> *const std::os::raw::c_char,
>;
pub type lua_Writer = Option<
    unsafe extern "C" fn(
        L: *mut lua_State,
        p: *const std::os::raw::c_void,
        sz: usize,
        ud: *mut std::os::raw::c_void,
    ) -> std::os::raw::c_int,
>;
pub type lua_Alloc = Option<
    unsafe extern "C" fn(
        ud: *mut std::os::raw::c_void,
        ptr: *mut std::os::raw::c_void,
        osize: usize,
        nsize: usize,
    ) -> *mut std::os::raw::c_void,
>;
pub type lua_Number = f64;
pub type lua_Integer = isize;
pub type lua_Hook = Option<unsafe extern "C" fn(L: *mut lua_State, ar: *mut lua_Debug)>;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct lua_Debug {
    pub event: std::os::raw::c_int,
    pub name: *const std::os::raw::c_char,
    pub namewhat: *const std::os::raw::c_char,
    pub what: *const std::os::raw::c_char,
    pub source: *const std::os::raw::c_char,
    pub currentline: std::os::raw::c_int,
    pub nups: std::os::raw::c_int,
    pub linedefined: std::os::raw::c_int,
    pub lastlinedefined: std::os::raw::c_int,
    pub short_src: [std::os::raw::c_char; 60usize],
    pub i_ci: std::os::raw::c_int,
}
pub type __builtin_va_list = [__va_list_tag; 1usize];
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct __va_list_tag {
    pub gp_offset: std::os::raw::c_uint,
    pub fp_offset: std::os::raw::c_uint,
    pub overflow_arg_area: *mut std::os::raw::c_void,
    pub reg_save_area: *mut std::os::raw::c_void,
}
#[gen_stubs]
#[link(name = "lua51")]
unsafe extern "C" {
    pub fn lua_newstate(f: lua_Alloc, ud: *mut std::os::raw::c_void) -> *mut lua_State;
    pub fn lua_close(L: *mut lua_State);
    pub fn lua_newthread(L: *mut lua_State) -> *mut lua_State;
    pub fn lua_atpanic(L: *mut lua_State, panicf: lua_CFunction) -> lua_CFunction;
    pub fn lua_gettop(L: *mut lua_State) -> std::os::raw::c_int;
    pub fn lua_settop(L: *mut lua_State, idx: std::os::raw::c_int);
    pub fn lua_pushvalue(L: *mut lua_State, idx: std::os::raw::c_int);
    pub fn lua_remove(L: *mut lua_State, idx: std::os::raw::c_int);
    pub fn lua_insert(L: *mut lua_State, idx: std::os::raw::c_int);
    pub fn lua_replace(L: *mut lua_State, idx: std::os::raw::c_int);
    pub fn lua_checkstack(L: *mut lua_State, sz: std::os::raw::c_int) -> std::os::raw::c_int;
    pub fn lua_xmove(from: *mut lua_State, to: *mut lua_State, n: std::os::raw::c_int);
    pub fn lua_isnumber(L: *mut lua_State, idx: std::os::raw::c_int) -> std::os::raw::c_int;
    pub fn lua_isstring(L: *mut lua_State, idx: std::os::raw::c_int) -> std::os::raw::c_int;
    pub fn lua_iscfunction(L: *mut lua_State, idx: std::os::raw::c_int) -> std::os::raw::c_int;
    pub fn lua_isuserdata(L: *mut lua_State, idx: std::os::raw::c_int) -> std::os::raw::c_int;
    pub fn lua_type(L: *mut lua_State, idx: std::os::raw::c_int) -> std::os::raw::c_int;
    pub fn lua_typename(L: *mut lua_State, tp: std::os::raw::c_int) -> *const std::os::raw::c_char;
    pub fn lua_equal(
        L: *mut lua_State,
        idx1: std::os::raw::c_int,
        idx2: std::os::raw::c_int,
    ) -> std::os::raw::c_int;
    pub fn lua_rawequal(
        L: *mut lua_State,
        idx1: std::os::raw::c_int,
        idx2: std::os::raw::c_int,
    ) -> std::os::raw::c_int;
    pub fn lua_lessthan(
        L: *mut lua_State,
        idx1: std::os::raw::c_int,
        idx2: std::os::raw::c_int,
    ) -> std::os::raw::c_int;
    pub fn lua_tonumber(L: *mut lua_State, idx: std::os::raw::c_int) -> lua_Number;
    pub fn lua_tointeger(L: *mut lua_State, idx: std::os::raw::c_int) -> lua_Integer;
    pub fn lua_toboolean(L: *mut lua_State, idx: std::os::raw::c_int) -> std::os::raw::c_int;
    pub fn lua_tolstring(
        L: *mut lua_State,
        idx: std::os::raw::c_int,
        len: *mut usize,
    ) -> *const std::os::raw::c_char;
    pub fn lua_objlen(L: *mut lua_State, idx: std::os::raw::c_int) -> usize;
    pub fn lua_tocfunction(L: *mut lua_State, idx: std::os::raw::c_int) -> lua_CFunction;
    pub fn lua_touserdata(L: *mut lua_State, idx: std::os::raw::c_int)
    -> *mut std::os::raw::c_void;
    pub fn lua_tothread(L: *mut lua_State, idx: std::os::raw::c_int) -> *mut lua_State;
    pub fn lua_topointer(
        L: *mut lua_State,
        idx: std::os::raw::c_int,
    ) -> *const std::os::raw::c_void;
    pub fn lua_pushnil(L: *mut lua_State);
    pub fn lua_pushnumber(L: *mut lua_State, n: lua_Number);
    pub fn lua_pushinteger(L: *mut lua_State, n: lua_Integer);
    pub fn lua_pushlstring(L: *mut lua_State, s: *const std::os::raw::c_char, l: usize);
    pub fn lua_pushstring(L: *mut lua_State, s: *const std::os::raw::c_char);
    pub fn lua_pushvfstring(
        L: *mut lua_State,
        fmt: *const std::os::raw::c_char,
        argp: *mut __va_list_tag,
    ) -> *const std::os::raw::c_char;
    pub fn lua_pushcclosure(L: *mut lua_State, fn_: lua_CFunction, n: std::os::raw::c_int);
    pub fn lua_pushboolean(L: *mut lua_State, b: std::os::raw::c_int);
    pub fn lua_pushlightuserdata(L: *mut lua_State, p: *mut std::os::raw::c_void);
    pub fn lua_pushthread(L: *mut lua_State) -> std::os::raw::c_int;
    pub fn lua_gettable(L: *mut lua_State, idx: std::os::raw::c_int);
    pub fn lua_getfield(
        L: *mut lua_State,
        idx: std::os::raw::c_int,
        k: *const std::os::raw::c_char,
    );
    pub fn lua_rawget(L: *mut lua_State, idx: std::os::raw::c_int);
    pub fn lua_rawgeti(L: *mut lua_State, idx: std::os::raw::c_int, n: std::os::raw::c_int);
    pub fn lua_createtable(L: *mut lua_State, narr: std::os::raw::c_int, nrec: std::os::raw::c_int);
    pub fn lua_newuserdata(L: *mut lua_State, sz: usize) -> *mut std::os::raw::c_void;
    pub fn lua_getmetatable(
        L: *mut lua_State,
        objindex: std::os::raw::c_int,
    ) -> std::os::raw::c_int;
    pub fn lua_getfenv(L: *mut lua_State, idx: std::os::raw::c_int);
    pub fn lua_settable(L: *mut lua_State, idx: std::os::raw::c_int);
    pub fn lua_setfield(
        L: *mut lua_State,
        idx: std::os::raw::c_int,
        k: *const std::os::raw::c_char,
    );
    pub fn lua_rawset(L: *mut lua_State, idx: std::os::raw::c_int);
    pub fn lua_rawseti(L: *mut lua_State, idx: std::os::raw::c_int, n: std::os::raw::c_int);
    pub fn lua_setmetatable(
        L: *mut lua_State,
        objindex: std::os::raw::c_int,
    ) -> std::os::raw::c_int;
    pub fn lua_setfenv(L: *mut lua_State, idx: std::os::raw::c_int) -> std::os::raw::c_int;
    pub fn lua_call(L: *mut lua_State, nargs: std::os::raw::c_int, nresults: std::os::raw::c_int);
    pub fn lua_pcall(
        L: *mut lua_State,
        nargs: std::os::raw::c_int,
        nresults: std::os::raw::c_int,
        errfunc: std::os::raw::c_int,
    ) -> std::os::raw::c_int;
    pub fn lua_cpcall(
        L: *mut lua_State,
        func: lua_CFunction,
        ud: *mut std::os::raw::c_void,
    ) -> std::os::raw::c_int;
    pub fn lua_load(
        L: *mut lua_State,
        reader: lua_Reader,
        dt: *mut std::os::raw::c_void,
        chunkname: *const std::os::raw::c_char,
    ) -> std::os::raw::c_int;
    pub fn lua_dump(
        L: *mut lua_State,
        writer: lua_Writer,
        data: *mut std::os::raw::c_void,
    ) -> std::os::raw::c_int;
    pub fn lua_yield(L: *mut lua_State, nresults: std::os::raw::c_int) -> std::os::raw::c_int;
    pub fn lua_resume(L: *mut lua_State, narg: std::os::raw::c_int) -> std::os::raw::c_int;
    pub fn lua_status(L: *mut lua_State) -> std::os::raw::c_int;
    pub fn lua_gc(
        L: *mut lua_State,
        what: std::os::raw::c_int,
        data: std::os::raw::c_int,
    ) -> std::os::raw::c_int;
    pub fn lua_error(L: *mut lua_State) -> std::os::raw::c_int;
    pub fn lua_next(L: *mut lua_State, idx: std::os::raw::c_int) -> std::os::raw::c_int;
    pub fn lua_concat(L: *mut lua_State, n: std::os::raw::c_int);
    pub fn lua_getallocf(L: *mut lua_State, ud: *mut *mut std::os::raw::c_void) -> lua_Alloc;
    pub fn lua_setallocf(L: *mut lua_State, f: lua_Alloc, ud: *mut std::os::raw::c_void);
    pub fn luaL_newstate() -> *mut lua_State;
    pub fn lua_getstack(
        L: *mut lua_State,
        level: std::os::raw::c_int,
        ar: *mut lua_Debug,
    ) -> std::os::raw::c_int;
    pub fn lua_getinfo(
        L: *mut lua_State,
        what: *const std::os::raw::c_char,
        ar: *mut lua_Debug,
    ) -> std::os::raw::c_int;
    pub fn lua_getlocal(
        L: *mut lua_State,
        ar: *const lua_Debug,
        n: std::os::raw::c_int,
    ) -> *const std::os::raw::c_char;
    pub fn lua_setlocal(
        L: *mut lua_State,
        ar: *const lua_Debug,
        n: std::os::raw::c_int,
    ) -> *const std::os::raw::c_char;
    pub fn lua_getupvalue(
        L: *mut lua_State,
        funcindex: std::os::raw::c_int,
        n: std::os::raw::c_int,
    ) -> *const std::os::raw::c_char;
    pub fn lua_setupvalue(
        L: *mut lua_State,
        funcindex: std::os::raw::c_int,
        n: std::os::raw::c_int,
    ) -> *const std::os::raw::c_char;
    pub fn lua_sethook(
        L: *mut lua_State,
        func: lua_Hook,
        mask: std::os::raw::c_int,
        count: std::os::raw::c_int,
    ) -> std::os::raw::c_int;
    pub fn lua_gethook(L: *mut lua_State) -> lua_Hook;
    pub fn lua_gethookmask(L: *mut lua_State) -> std::os::raw::c_int;
    pub fn lua_gethookcount(L: *mut lua_State) -> std::os::raw::c_int;
    pub fn lua_upvalueid(
        L: *mut lua_State,
        idx: std::os::raw::c_int,
        n: std::os::raw::c_int,
    ) -> *mut std::os::raw::c_void;
    pub fn lua_upvaluejoin(
        L: *mut lua_State,
        idx1: std::os::raw::c_int,
        n1: std::os::raw::c_int,
        idx2: std::os::raw::c_int,
        n2: std::os::raw::c_int,
    );
    pub fn lua_loadx(
        L: *mut lua_State,
        reader: lua_Reader,
        dt: *mut std::os::raw::c_void,
        chunkname: *const std::os::raw::c_char,
        mode: *const std::os::raw::c_char,
    ) -> std::os::raw::c_int;
}
